export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[#050604] px-5 py-10 text-white md:px-8">
      <div className="mx-auto max-w-4xl">
        <a
          href="/"
          className="inline-flex items-center gap-2 text-sm text-zinc-500 transition hover:text-[#a8f5a5]"
        >
          ← Back to Vantage
        </a>

        <div className="mt-10 rounded-3xl border border-white/10 bg-white/[0.025] p-6 md:p-10">
          <div className="muted-label">Legal</div>

          <h1 className="mt-3 text-4xl font-semibold tracking-tight text-white">
            Terms of Service
          </h1>

          <p className="mt-4 text-sm leading-7 text-zinc-500">
            Last updated: August 2026
          </p>

          <div className="mt-10 space-y-8 text-sm leading-7 text-zinc-400">
            <section>
              <h2 className="text-lg font-semibold text-white">
                1. Overview
              </h2>

              <p className="mt-3">
                Vantage is a financial document intelligence platform designed
                to analyze SEC filings, compare reporting periods, retrieve
                supporting evidence, and generate structured reports. The
                platform is currently intended for demonstration, research, and
                development purposes.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white">
                2. No Financial Advice
              </h2>

              <p className="mt-3">
                Vantage does not provide investment, financial, legal, tax, or
                accounting advice. Reports generated by the platform are for
                informational purposes only and should not be relied upon as the
                sole basis for investment decisions.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white">
                3. Accuracy of Information
              </h2>

              <p className="mt-3">
                Vantage processes public filing data and generated analysis.
                While the platform is designed to provide evidence-backed
                summaries, outputs may contain errors, omissions, or incomplete
                interpretations. Users should verify important information
                directly from original SEC filings and other authoritative
                sources.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white">
                4. Use of the Platform
              </h2>

              <p className="mt-3">
                Users agree to use Vantage responsibly and not attempt to misuse,
                disrupt, reverse engineer, overload, or interfere with the
                platform, its APIs, or connected services.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white">
                5. Third-Party Services
              </h2>

              <p className="mt-3">
                Vantage may rely on third-party services for data retrieval,
                AI-generated outputs, embeddings, infrastructure, and other
                functionality. Availability, accuracy, and performance may depend
                on those external services.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white">
                6. Limitation of Liability
              </h2>

              <p className="mt-3">
                Vantage is provided as-is without warranties of any kind. The
                developers are not liable for decisions, losses, damages, or
                outcomes resulting from use of the platform or reliance on its
                generated outputs.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white">
                7. Changes to These Terms
              </h2>

              <p className="mt-3">
                These terms may be updated as the project evolves. Continued use
                of the platform after updates means acceptance of the revised
                terms.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white">
                8. Contact
              </h2>

              <p className="mt-3">
                For questions about Vantage, contact the project maintainer
                through the repository or project profile.
              </p>
            </section>
          </div>
        </div>
      </div>
    </main>
  );
}